apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-bucket-app
spec:
  project: default
  source:
    repoURL: https://github.com/azaurus1/gitops-crossplane-example
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default