{{- range $index, $bucket := .Values.buckets}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $bucket.name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/azaurus1/gitops-crossplane-example
    targetRevision: HEAD
    path: buckets/{{$bucket.name}}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
{{- end }}